version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: